name: stripe_apple_pay
description: Create chargeable stripe tokens using Apple Pay
version: 1.0.0
repository: https://github.com/sofferjacob/stripe_apple_pay

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: StripeNativePlugin

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'